//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioVelo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdminFee
    {
        public long Id { get; set; }
        public Nullable<double> InsuranceFor1Day { get; set; }
        public Nullable<double> InsuranceFor2to3Days { get; set; }
        public Nullable<double> InsuranceFor4to6Days { get; set; }
        public Nullable<double> InsuranceFor7to10Days { get; set; }
        public Nullable<double> InsuranceForMoreThan10Days { get; set; }
        public Nullable<double> BookingFeeRenter { get; set; }
        public Nullable<double> BookingFeeOwner { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
