//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioVelo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDispute
    {
        public long Id { get; set; }
        public Nullable<long> RaisedBy { get; set; }
        public Nullable<long> RaisedFor { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> BookingId { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsResolved { get; set; }
    
        public virtual tblBooking tblBooking { get; set; }
    }
}
