//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioVelo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEquipment()
        {
            this.tblImages = new HashSet<tblImage>();
        }
    
        public long Id { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MaxHeight { get; set; }
        public Nullable<decimal> MinHeight { get; set; }
        public string Size { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public Nullable<bool> IsOtherBrand { get; set; }
        public string OtherBrand { get; set; }
        public Nullable<bool> IsVintage { get; set; }
        public string PurchaseYear { get; set; }
        public string BicyclePurchaseValue { get; set; }
        public string AboutBike { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImage> tblImages { get; set; }
    }
}
