//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioVelo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRating
    {
        public long Id { get; set; }
        public Nullable<long> RatedBy { get; set; }
        public Nullable<long> RatedTo { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Review { get; set; }
        public Nullable<long> BookingId { get; set; }
        public Nullable<bool> IsOwnerRating { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
