//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioVelo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<long> LoginId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string OTP { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> IsExpired { get; set; }
        public Nullable<int> IsVerified { get; set; }
        public string FacebookId { get; set; }
        public Nullable<int> Age { get; set; }
        public string CountryCode { get; set; }
        public string DeemlyId { get; set; }
        public string ImageName { get; set; }
        public string QuickBlox_UserId { get; set; }
        public string AccountId { get; set; }
        public string OnfidoId { get; set; }
        public Nullable<int> FineAmount { get; set; }
        public Nullable<int> CreditAmount { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
        public string CheckId { get; set; }
        public string ReportId { get; set; }
        public Nullable<bool> IsDocumentUploaded { get; set; }
        public Nullable<bool> IsOnfidoVerified { get; set; }
        public Nullable<int> Count { get; set; }
        public string OnfidoResult { get; set; }
        public Nullable<System.DateTime> LastOnfidoFailedTime { get; set; }
        public string TimeZone { get; set; }
        public string AboutMe { get; set; }
        public string BankAccountId { get; set; }
        public string BankAccountNo { get; set; }
    }
}
